research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

k8s_pods_overview:
  description: >
    Use kubectl_tool to get a compact overview of Pods in {namespace} with labels {selector}.
    Return a short table: NAME | READY | STATUS | AGE | NODE (if available).
  expected_output: >
    Markdown table with 5-20 rows. Include quick insights (CrashLoopBackOff counts).
  agent: k8s_operator
  inputs:
    namespace: default
    selector: app={topic}

k8s_error_logs:
  description: >
    If any pods look unhealthy, call kubectl_tool(action="logs") for the first one.
    Tail {tail} lines. Summarize top 5 repeating errors.
  expected_output: >
    Bullet list of the top errors with counts + 10-line excerpt.
  agent: k8s_operator
  inputs:
    tail: 300

