steps:
  - run: k8s_top_nodes
  - run: k8s_top_pods_ns_default
  - run: k8s_pods_overview
  - run: explain_pods
  - run: cluster_summary
  - run: k8s_events_recent
  - run: argocd_list_apps
  - run: argocd_app_status_chat_api
  - run: loki_recent_errors_chat_api
  - run: loki_http_activity_chat_api
  - run: incident_create_issue_if_needed
